include:
  - docker.d/servers_and_tools_builder/docker-compose.yaml
version: '3'
services:
  databases:
    build:
      context: ./docker.d/databases
      dockerfile: databases.Dockerfile
      tags:
        - ${NAMESPACE}.trinitycore.databases:${DATABASES_VERSION}
    entrypoint: /root/scripts/databases-entrypoint.sh
    init: true
    networks:
      - inside
    volumes:
      - type: volume
        source: databases_data
        target: /var/lib/mysql/data
  worldserver:
    depends_on:
      - databases
    entrypoint: /home/trinitycore/scripts/worldserver-entrypoint.sh
    image: ${NAMESPACE}.trinitycore.worldserver:${WORLDSERVER_VERSION}
    init: true
    networks:
      - inside
    volumes:
      - type: volume
        source: worldserver_downloads
        target: /home/trinitycore/downloads
      - type: volume
        source: client_data
        target: /home/trinitycore/trinitycore/data
        read_only: true
      - type: volume
        source: trinitycore_sources
        target: /home/trinitycore/TrinityCore
      - type: volume
        source: trinitycore_configurations
        target: /home/trinitycore/trinitycore/etc
        volume:
          nocopy: true
  # authserver:
  #   depends_on:
  #   - worldserver
  #   entrypoint: /home/docker/authserver-entrypoint.sh
  #   image: ${NAMESPACE}.trinitycore.authserver:${AUTHSERVER_VERSION}
  #   init: true
volumes:
  databases_data:
  worldserver_downloads:
networks:
  inside:
