include:
  - docker.d/servers_and_tools_builder/docker-compose.yaml
version: '3'
services:
  databases:
    build:
      context: ./docker.d/databases
      dockerfile: databases.Dockerfile
      tags:
        - ${NAMESPACE}.trinitycore.databases:${DATABASES_VERSION}
    entrypoint: /root/scripts/databases-entrypoint.sh
    healthcheck:
      test: ['CMD-SHELL', '/root/scripts/healthcheck.sh']
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 2s
      start_interval: 1s
    init: true
    networks:
      - inside
    volumes:
      - type: volume
        source: databases_data
        target: /var/lib/mysql/data
      - type: volume
        source: trinitycore_sources
        target: /root/TrinityCore
  worldserver:
    depends_on:
      databases:
        condition: service_healthy
    entrypoint: /home/trinitycore/scripts/worldserver-entrypoint.sh
    image: ${NAMESPACE}.trinitycore.worldserver:${WORLDSERVER_VERSION}
    init: true
    networks:
      - inside
    volumes:
      - type: volume
        source: worldserver_downloads
        target: /home/trinitycore/downloads
      - type: volume
        source: client_data
        target: /home/trinitycore/trinitycore/data
        read_only: true
      - type: volume
        source: trinitycore_sources
        target: /home/trinitycore/TrinityCore
  # authserver:
  #   depends_on:
  #   - worldserver
  #   entrypoint: /home/docker/authserver-entrypoint.sh
  #   image: ${NAMESPACE}.trinitycore.authserver:${AUTHSERVER_VERSION}
  #   init: true
volumes:
  databases_data:
  worldserver_downloads:
networks:
  inside:
