version: "3"
services:
  databases:
    init: true
    build:
      context: ./docker.d/databases
      dockerfile: databases.Dockerfile
      tags:
        - ${FQDN}/trinitycore/databases:${DATABASES_VERSION}
    volumes:
      - type: volume
        source: databases_data
        target: /var/lib/mysql/data
  servers_and_tools_builder:
    init: true
    build:
      context: ./docker.d/servers_and_tools_builder
      dockerfile: servers_and_tools_builder.Dockerfile
      args:
        - DOCKER_GID
        - DOCKER_UID
      tags:
        - ${FQDN}/trinitycore/servers_and_tools_builder:${SERVERS_AND_TOOLS_BUILDER_VERSION}
    environment:
      - SERVERS_AND_TOOLS_BUILDER_IMAGE=${FQDN}/trinitycore/servers_and_tools_builder:${SERVERS_AND_TOOLS_BUILDER_VERSION}
      - AUTHSERVER_IMAGE_TAG=${FQDN}/trinitycore/authserver:${AUTHSERVER_VERSION}
    entrypoint: /home/docker/servers_and_tools_builder-entrypoint.sh
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
volumes:
  databases_data:
