version: "3"
services:
  databases:
    build:
      context: ./docker.d/databases
      dockerfile: databases.Dockerfile
      tags:
        - ${FQDN}/trinitycore/databases:${DATABASES_VERSION}
    volumes:
      - type: volume
        source: databases_data
        target: /var/lib/mysql/data
  authserver:
    build:
      context: ./docker.d/authserver
      dockerfile: authserver.Dockerfile
      tags:
        - ${FQDN}/trinitycore/authserver:${AUTHSERVER_VERSION}
  worldserver:
    build:
      context: ./docker.d/worldserver
      dockerfile: worldserver.Dockerfile
      tags:
        - ${FQDN}/trinitycore/worldserver:${WORLDSERVER_VERSION}
volumes:
  databases_data:
