version: "3"
services:
  databases:
    build:
      context: ./docker.d/databases
      dockerfile: databases.Dockerfile
      tags:
        - ${FQDN}/trinitycore/databases:${DATABASES_VERSION}
    volumes:
      - type: volume
        source: databases_data
        target: /var/lib/mysql/data
  servers_and_tools_builder:
    build:
      context: ./docker.d/servers_and_tools_builder
      dockerfile: servers_and_tools_builder.Dockerfile
      args:
        - DOCKER_GID
        - DOCKER_UID
      tags:
        - ${FQDN}/trinitycore/servers_and_tools_builder:${SERVERS_AND_TOOLS_BUILDER_VERSION}
volumes:
  databases_data:
