version: "3"
services:
  databases:
    build:
      context: ./docker.d/databases
      dockerfile: databases.Dockerfile
      tags:
        - ${FQDN}/trinitycore/databases:${DATABASES_VERSION}
    volumes:
      - type: volume
        source: databases_data
        target: /var/lib/mysql/data
  servers:
    build:
      context: ./docker.d/servers
      dockerfile: servers.Dockerfile
      tags:
        - ${FQDN}/trinitycore/servers:${SERVERS_VERSION}
volumes:
  databases_data:
