include:
  - docker.d/maintainer.docker-compose.yaml
services:
  databases:
    build:
      args:
        - COMPOSE_PROJECT_NAME
        - NAMESPACE
      context: ./docker.d/databases
      dockerfile: databases.Dockerfile
      tags:
        - ${NAMESPACE}.databases:${DATABASES_VERSION}
    entrypoint: /root/scripts/databases-entrypoint.sh
    healthcheck:
      test: ['CMD-SHELL', '/root/scripts/healthcheck.sh']
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 2s
      start_interval: 1s
    init: true
    networks:
      inside:
        ipv4_address: 11.12.13.1
    volumes:
      - type: volume
        source: databases_data
        target: /var/lib/mysql/data
      - type: volume
        source: trinitycore_shallow_clone
        target: /root/TrinityCore
  worldserver:
    depends_on:
      databases:
        condition: service_healthy
    entrypoint: /home/trinitycore/scripts/worldserver-entrypoint.sh
    environment:
      - REALMLIST_ADDRESS
      - TDB_FULL_URI
      - TDB_FULL_ARCHIVE_FILE_NAME
      - TDB_FULL_SQL_FILE_NAME
    image: ${NAMESPACE}.worldserver:${WORLDSERVER_VERSION}
    init: true
    networks:
      inside:
        ipv4_address: 11.12.13.2
    ports:
      - target: 8085
        host_ip: 0.0.0.0
        published: '8085'
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: worldserver_downloads
        target: /home/trinitycore/downloads
      - type: volume
        source: client_data
        target: /home/trinitycore/trinitycore/data
        read_only: true
      - type: volume
        source: trinitycore_shallow_clone
        target: /home/trinitycore/TrinityCore
  worldserver_console:
    build:
      args:
        - COMPOSE_PROJECT_NAME
        - NAMESPACE
      context: ./docker.d/worldserver_console
      dockerfile: worldserver_console.Dockerfile
      tags:
        - ${NAMESPACE}.worldserver_console:${WORLDSERVER_CONSOLE_VERSION}
    depends_on:
      - worldserver
    entrypoint: /home/worldserver_console/scripts/worldserver_console-entrypoint.sh
    environment:
      - ADMIN_ACCOUNT_NAME
      - ADMIN_ACCOUNT_PASSWORD
    healthcheck:
      test: ['CMD-SHELL', '/home/worldserver_console/scripts/healthcheck.sh']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
      start_interval: 10s
    init: true
    networks:
      inside:
        ipv4_address: 11.12.13.3
  authserver:
    depends_on:
      databases:
        condition: service_healthy
    entrypoint: /home/trinitycore/scripts/authserver-entrypoint.sh
    image: ${NAMESPACE}.authserver:${AUTHSERVER_VERSION}
    init: true
    networks:
      inside:
        ipv4_address: 11.12.13.4
    ports:
      - target: 3724
        host_ip: 0.0.0.0
        published: '3724'
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: trinitycore_shallow_clone
        target: /home/trinitycore/TrinityCore
volumes:
  databases_data:
  worldserver_downloads:
networks:
  inside:
    ipam:
      driver: default
      config:
        - subnet: 11.12.13.0/29
          ip_range: 11.12.13.0/29
          gateway: 11.12.13.6
