include:
  - docker.d/servers_and_tools_builder/docker-compose.yaml
version: '3'
services:
  databases:
    init: true
    build:
      context: ./docker.d/databases
      dockerfile: databases.Dockerfile
      tags:
        - ${FQDN}/trinitycore/databases:${DATABASES_VERSION}
    entrypoint: /root/scripts/databases-entrypoint.sh
    volumes:
      - type: volume
        source: databases_data
        target: /var/lib/mysql/data
  # worldserver:
  #   init: true
  #   depends_on: database
  #   image: ${FQDN}/trinitycore/worldserver
  #   entrypoint: /home/docker/worldserver-entrypoint.sh
  # authserver:
  #   init: true
  #   depends_on: worldserver
  #   image: ${FQDN}/trinitycore/authserver
  #   entrypoint: /home/docker/authserver-entrypoint.sh
volumes:
  databases_data:
