ARG NAMESPACE

FROM $NAMESPACE.builderbase
ARG USER
ARG USER_HOME_DIR
WORKDIR $USER_HOME_DIR
COPY \
  --chown=$USER:$USER \
  --chmod=755 \
  scripts scripts
RUN mkdir $USER_HOME_DIR/TrinityCore
RUN chown -R $USER:$USER $USER_HOME_DIR/TrinityCore
VOLUME $USER_HOME_DIR/TrinityCore
RUN mkdir $USER_HOME_DIR/data
RUN chown -R $USER:$USER $USER_HOME_DIR/data
VOLUME $USER_HOME_DIR/data
USER $USER
