services:
  builder:
    container_name: ${COMPOSE_PROJECT_NAME}_builder
    entrypoint: scripts/builder_entrypoint.sh
    environment:
      - BUILDERBASE_VERSION
      - CLIENT_PATH
      - COMPOSE_PROJECT_NAME
      - NAMESPACE
      - SERVERBASE_VERSION
      - USE_CACHED_CLIENT_DATA
      - USER_HOME_DIR
    image: ${NAMESPACE}.builder:${BUILDER_VERSION}
    init: true
    network_mode: none
    profiles:
      - internal
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: ${CLIENT_PATH}
        target: ${USER_HOME_DIR:-implementation defined}/WoW-3.3.5a-12340
      - type: volume
        source: client_data
        target: ${USER_HOME_DIR:-implementation defined}/data
      - type: volume
        source: wsl2_client_copy
        target: ${USER_HOME_DIR:-implementation defined}/wsl2_client_copy
      - type: volume
        source: trinitycore_shallow_clone
        target: ${USER_HOME_DIR:-implementation defined}/TrinityCore
  ide:
    container_name: ${COMPOSE_PROJECT_NAME}_ide
    entrypoint: scripts/ide_entrypoint.sh
    environment:
      - DEBUG_AUTH_DATABASE_NAME
      - DEBUG_AUTHSERVER_PORT
      - DEBUG_CHARACTERS_DATABASE_NAME
      - DEBUG_REALM_ID
      - DEBUG_REALM_NAME
      - DEBUG_REALMLIST_ADDRESS
      - DEBUG_WORLD_DATABASE_NAME
      - DEBUG_WORLDSERVER_PORT
      - GAMESERVERS_VERSION
      - GIT_USER_EMAIL
      - GIT_USER_NAME
      - NAMESPACE
      - REPOSITORY_REV
      - REPOSITORY_SHA
      - REPOSITORY_URI
      - TDB_FULL_URI
      - TRINITYCORE_INSTALL_DIRECTORY
      - TRINITYCORE_REPOSITORY_TARGET_DIRECTORY
    hostname: ide
    image: ${NAMESPACE}.ide:${IDE_VERSION}
    init: true
    networks:
      inside:
        ipv4_address: 11.12.13.5
    ports:
      - target: ${DEBUG_WORLDSERVER_PORT}
        host_ip: 0.0.0.0
        published: ${DEBUG_WORLDSERVER_PORT}
        protocol: tcp
        mode: host
      - target: ${DEBUG_AUTHSERVER_PORT}
        host_ip: 0.0.0.0
        published: ${DEBUG_AUTHSERVER_PORT}
        protocol: tcp
        mode: host
    profiles:
      - dev
    secrets:
      - ide_ssh_public_key
      - ide_ssh_secret_key
    ulimits:
      core:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: ${CLIENT_PATH}
        target: ${CLIENT_PATH}
        read_only: true
      - type: volume
        source: client_data
        target: ${USER_HOME_DIR:-implementation defined}/client_data
      - type: volume
        source: ide_storage
        target: ${USER_HOME_DIR:-implementation defined}/ide_storage
      - type: volume
        source: ide_npm_prefix
        target: ${USER_HOME_DIR:-implementation defined}/.npm-prefix
        volume:
          nocopy: false
      - type: volume
        source: ide_npm_cache
        target: ${USER_HOME_DIR:-implementation defined}/.npm-cache
        volume:
          nocopy: false
      - type: volume
        source: ide_xdg_init
        target: ${USER_HOME_DIR:-implementation defined}/.init
        volume:
          nocopy: false
      - type: volume
        source: ide_xdg_local
        target: ${USER_HOME_DIR:-implementation defined}/.local
        volume:
          nocopy: false
secrets:
  ide_ssh_public_key:
    file: ${SSH_PUBLIC_KEY_FILE_PATH}
  ide_ssh_secret_key:
    file: ${SSH_SECRET_KEY_FILE_PATH}
volumes:
  client_data:
  ide_storage:
  trinitycore_shallow_clone:
  wsl2_client_copy:
  ide_npm_prefix:
  ide_npm_cache:
  ide_xdg_init:
  ide_xdg_local:
