services:
  builder:
    # TODO: remove all build stuff from compose. Build is for make, run is for compose
    build:
      args:
        - COMPOSE_PROJECT_NAME
        - NAMESPACE
        - REPOSITORY_URI
        - REPOSITORY_REV
        - REPOSITORY_SHA
        - USER
        - USER_GID
        - USER_HOME_DIR
        - USER_UID
      context: builder
      dockerfile: builder.Dockerfile
      ssh:
        - default
      tags:
        - ${NAMESPACE}.builder:${BUILDER_VERSION}
    entrypoint: scripts/builder_entrypoint.sh
    environment:
      - AUTHSERVER_IMAGE_TAG=${NAMESPACE}.authserver:${AUTHSERVER_VERSION}
      - BUILDER_IMAGE=${NAMESPACE}.builder:${BUILDER_VERSION}
      - CLIENT_PATH
      - COMPOSE_PROJECT_NAME
      - NAMESPACE
      - SHELL=/bin/bash
      - USE_CACHED_CLIENT_DATA
      - USER_HOME_DIR
      - WORLDSERVER_CONF_PATH
      - WORLDSERVER_IMAGE_TAG=${NAMESPACE}.worldserver:${WORLDSERVER_VERSION}
    init: true
    network_mode: none
    profiles:
      - internal
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: ${CLIENT_PATH}
        target: ${USER_HOME_DIR:-implementation defined}/WoW-3.3.5a-12340
      - type: volume
        source: client_data
        target: ${USER_HOME_DIR:-implementation defined}/data
      - type: volume
        source: wsl2_client_copy
        target: ${USER_HOME_DIR:-implementation defined}/wsl2_client_copy
      - type: volume
        source: trinitycore_shallow_clone
        target: ${USER_HOME_DIR:-implementation defined}/TrinityCore
  ide:
    build:
      args:
        - COMPOSE_PROJECT_NAME
        - IDE_NEOVIM_REV
        - NAMESPACE
        - NODEJS_VER
        - USER
        - USER_HOME_DIR
      context: ide
      dockerfile: ide.Dockerfile
      tags:
        - ${NAMESPACE}.ide:${IDE_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_ide_container
    entrypoint: scripts/ide_entrypoint.sh
    environment:
      - BUILDER_VERSION
      - GIT_USER_EMAIL
      - GIT_USER_NAME
      - NAMESPACE
      - REPOSITORY_REV
      - REPOSITORY_SHA
      - REPOSITORY_URI
      - TRINITYCORE_INSTALL_DIRECTORY
      - TRINITYCORE_REPOSITORY_TARGET_DIRECTORY
      - USER_HOME_DIR
    hostname: ide
    init: true
    networks:
      dev:
      inside:
        ipv4_address: 11.12.13.5
    #TODO: make exposed ports configurable (after research on how ports work for trinitycore)
    ports:
      - target: 8085
        host_ip: 0.0.0.0
        published: '8085'
        protocol: tcp
        mode: host
      - target: 3724
        host_ip: 0.0.0.0
        published: '3724'
        protocol: tcp
        mode: host
    profiles:
      - dev
    secrets:
      - ide_ssh_public_key
      - ide_ssh_secret_key
    ulimits:
      core:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: ${CLIENT_PATH}
        target: ${CLIENT_PATH}
        read_only: true
      - type: volume
        source: client_data
        target: ${USER_HOME_DIR:-implementation defined}/client_data
      - type: volume
        source: ide_storage
        target: ${USER_HOME_DIR:-implementation defined}/ide_storage
      - type: volume
        source: ide_npm_prefix
        target: ${USER_HOME_DIR:-implementation defined}/.npm-prefix
        volume:
          nocopy: false
      - type: volume
        source: ide_npm_cache
        target: ${USER_HOME_DIR:-implementation defined}/.npm-cache
        volume:
          nocopy: false
      - type: volume
        source: ide_xdg_init
        target: ${USER_HOME_DIR:-implementation defined}/.init
        volume:
          nocopy: false
      - type: volume
        source: ide_xdg_local
        target: ${USER_HOME_DIR:-implementation defined}/.local
        volume:
          nocopy: false
networks:
  dev:
secrets:
  ide_ssh_public_key:
    file: ${SSH_PUBLIC_KEY_FILE_PATH}
  ide_ssh_secret_key:
    file: ${SSH_SECRET_KEY_FILE_PATH}
volumes:
  client_data:
  ide_storage:
  trinitycore_shallow_clone:
  wsl2_client_copy:
  ide_npm_prefix:
  ide_npm_cache:
  ide_xdg_init:
  ide_xdg_local:
